services:
  - type: web
    name: hofixx-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: MONGODB_URI
        sync: false  # Set this manually in Render dashboard
      - key: REDIS_URL
        sync: false  # Set this manually in Render dashboard
      - key: RAZORPAY_KEY_ID
        sync: false  # Set this manually in Render dashboard
      - key: RAZORPAY_KEY_SECRET
        sync: false  # Set this manually in Render dashboard

databases:
  - name: hofixx-redis
    plan: free
    type: redis
